### PR TITLE
CLDC-628 Household characteristics

### PR DESCRIPTION
**Pull request by roobottom**
This version of **Household Characteristics** allows the user to add up to three tenants. 

We need to test this, as it already feels pretty burdensome. My gut is that if the code checks out, let's just merge this in and see what the rest of the team think before we put it in front of users.

### CODE REVIEW

**Comment by roobottom** [comment]
@paulrobertlloyd Please don't merge this yet, creating a PR so I can share the link.

**Comment by roobottom** [comment]
@paulrobertlloyd I have no idea why this contains a bunch of your commits. These already seem to be in the main branch. Maybe git just layers over the history till this point? For example, your commit [9ef7d4c](https://github.com/communitiesuk/core-prototype/pull/22/commits/9ef7d4c12d96c1230b14d01b3052c174fe2b5c50) is already in `app/layouts/check-answers.njk`. Maybe just merge this in?

**Comment by paulrobertlloyd** [comment]
> @paulrobertlloyd I have no idea why this contains a bunch of your commits. These already seem to be in the main branch. Maybe git just layers over the history till this point? For example, your commit [9ef7d4c](https://github.com/communitiesuk/core-prototype/pull/22/commits/9ef7d4c12d96c1230b14d01b3052c174fe2b5c50) is already in `app/layouts/check-answers.njk`. Maybe just merge this in?

Don’t worry, about to open a new PR with this all fixed 🙂

**Comment by paulrobertlloyd** [comment]
Replaced by #28.

**Pull request closed without merging**
